name:                Automata
version:             0.1.0.0
github:              "Isaac-DeFrain/Automata"
license:             BSD3
author:              "Isaac DeFrain"
maintainer:          "isaacdefrain@gmail.com"
copyright:           "APACHE-2.0"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Isaac-DeFrain/Automata#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hspec
- QuickCheck

default-extensions:
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - StandaloneDeriving

library:
  source-dirs: src

executables:
  Automata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Automata

tests:
  Automata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Automata
